[package]
name = "cas3"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
reqwest = { version = "0.11", features = ["blocking"] }
sha2 = "0.10"
digest = "0.10"
tempfile = "3.5"
url = "2.5"
hex = "0.4"
[dev-dependencies]
httpmock = "0.7"
